version: '3.8'

services:
  ocr:
    build: ./services/ocr
    container_name: ocr
    ports:
      - "5002:5000"
    restart: always

  classifier:
    build: ./services/classifier
    container_name: classifier
    ports:
      - "5001:5000"
    depends_on:
      - ocr
    restart: always
