services:
  ocr:
    build: ./services/ocr
    container_name: ocr
    ports:
      - "5002:5000"
    restart: always

  classifier:
    build: ./services/classifier
    container_name: classifier
    ports:
      - "5001:5000"
    depends_on:
      - ocr
    restart: always
    volumes:
      - ./services/classifier:/app
      - ./services/classifier/live_session.session:/app/live_session.session
  listener:
    build: ./services/telegram-listener
    container_name: telegram-listener
    depends_on:
      - classifier
    restart: always
    volumes:
      - ./services/telegram-listener:/app
      - ./services/telegram-listener/live_session.session:/app/live_session.session
